# Generated by Django 4.0.6 on 2022-09-20 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=80)),
                ('pno', models.IntegerField(max_length=10)),
                ('query', models.TextField(max_length=300)),
            ],
        ),
    ]
