# Generated by Django 4.0.6 on 2022-09-20 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Username',
            new_name='name',
        ),
    ]
