# Generated by Django 4.0.6 on 2022-09-21 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0004_remove_contact_pno_remove_contact_query_contact_desc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hname', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=540)),
                ('ambno', models.CharField(max_length=250)),
                ('dname', models.CharField(max_length=340)),
                ('phone', models.CharField(max_length=120)),
            ],
        ),
    ]
