# Generated by Django 4.1.1 on 2022-10-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0006_city_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='area',
            field=models.CharField(max_length=90, null='True'),
            preserve_default='True',
        ),
    ]
