# Generated by Django 4.1.1 on 2022-10-04 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0007_hospital_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookambulance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=90)),
                ('lname', models.CharField(max_length=90)),
                ('hname', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=350)),
                ('uphone', models.CharField(max_length=100)),
                ('tambulance', models.CharField(max_length=90)),
                ('age', models.CharField(max_length=3)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
            ],
        ),
    ]
