# Generated by Django 4.1.1 on 2022-10-04 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0008_bookambulance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookambulance',
            name='hname',
        ),
    ]
