# Generated by Django 4.1.1 on 2022-10-04 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0009_remove_bookambulance_hname'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookambulance',
            name='hname',
            field=models.CharField(max_length=500, null='True'),
            preserve_default='True',
        ),
    ]
