# Generated by Django 3.2 on 2022-10-10 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0011_remove_bookambulance_hname_bookambulance_hospital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookambulance',
            name='hospital',
        ),
        migrations.AddField(
            model_name='bookambulance',
            name='hname',
            field=models.CharField(max_length=90, null='True'),
            preserve_default='True',
        ),
    ]
