# Generated by Django 3.2 on 2022-10-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0014_alter_bookambulance_tambulance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookambulance',
            name='tambulance',
            field=models.CharField(choices=[('1', 'Basic Ambulance'), ('2', 'Advance Ambulance'), ('3', 'Mortuary Ambulance'), ('4', 'Patient Transport Vehicle'), ('5', 'Air Ambulance')], default='0', max_length=20),
        ),
    ]
