# Generated by Django 3.2 on 2023-03-20 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0015_alter_bookambulance_tambulance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospitaldetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hname', models.CharField(max_length=250)),
                ('htype', models.CharField(choices=[('1', 'Basic Ambulance'), ('2', 'Advance Ambulance')], default='0', max_length=20)),
                ('haddress', models.CharField(max_length=350)),
                ('hcontact', models.CharField(max_length=450)),
                ('hemail', models.CharField(max_length=150)),
                ('ambno', models.CharField(max_length=160)),
                ('dname', models.CharField(max_length=160)),
                ('dphone', models.CharField(max_length=150)),
                ('pass1', models.CharField(max_length=150)),
                ('pass2', models.CharField(max_length=150)),
            ],
        ),
    ]
