# Generated by Django 3.2 on 2023-03-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0016_hospitaldetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitaldetails',
            name='htype',
            field=models.CharField(choices=[('1', 'Private'), ('2', 'goverments')], default='0', max_length=20),
        ),
    ]
