# Generated by Django 4.1.7 on 2023-05-16 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0017_alter_hospitaldetails_htype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fac1', models.CharField(max_length=120)),
                ('fac2', models.CharField(max_length=120)),
                ('fac3', models.CharField(max_length=120)),
                ('fac4', models.CharField(max_length=120)),
                ('fac5', models.CharField(max_length=120)),
            ],
        ),
        migrations.AlterField(
            model_name='bookambulance',
            name='gender',
            field=models.CharField(choices=[('1', 'Male'), ('2', 'Female')], default='0', max_length=1),
        ),
    ]
