# Generated by Django 4.1.7 on 2023-05-16 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0018_basic_alter_bookambulance_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='fac1',
            field=models.CharField(default='0', max_length=120),
        ),
        migrations.AddField(
            model_name='area',
            name='fac2',
            field=models.CharField(default='0', max_length=120),
        ),
        migrations.AddField(
            model_name='area',
            name='fac3',
            field=models.CharField(default='0', max_length=120),
        ),
        migrations.AddField(
            model_name='area',
            name='fac4',
            field=models.CharField(default='0', max_length=120),
        ),
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
