# Generated by Django 4.1.7 on 2023-05-17 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0019_area_fac1_area_fac2_area_fac3_area_fac4_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=120)),
                ('name', models.CharField(default='0', max_length=50)),
                ('fac1', models.CharField(default='0', max_length=120)),
                ('fac2', models.CharField(default='0', max_length=120)),
                ('fac3', models.CharField(default='0', max_length=120)),
                ('fac4', models.CharField(default='0', max_length=120)),
            ],
        ),
    ]
